### ISSUE TITLE
`Error: Cannot find module 'opencv4nodejs'` when running build on RHEL node on Jenkins

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1437]
```
[Pipeline] {
[Pipeline] sh
+ npm run ui-test

> vscode-openshift-connector@0.1.4 ui-test /mnt/hudson_workspace/workspace/vscode-openshift-build
> extest setup-and-run out/test/ui/*.test.js

/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/cv.js:14
  throw err
  ^

Error: Cannot find module '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs'
Require stack:
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/cv.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/opencv4nodejs.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/lib/provider/opencv/image-writer.class.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/lib/adapter/vision.adapter.class.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/index.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/webdriver/native/openDialog.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/webdriver/native/dialogHandler.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/extester.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/cv.js:11:8)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/cv.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/opencv4nodejs.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/lib/provider/opencv/image-writer.class.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/lib/adapter/vision.adapter.class.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/index.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/webdriver/native/openDialog.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/webdriver/native/dialogHandler.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/extester.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/cli.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-openshift-connector@0.1.4 ui-test: `extest setup-and-run out/test/ui/*.test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vscode-openshift-connector@0.1.4 ui-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hudson/.npm/_logs/2020-03-13T19_44_59_967Z-debug.log

[Pipeline] }
Terminating xvnc.
```

**Comment by dgolovin** [comment]
Resolved with #1471.
