### ISSUE TITLE
rejected promise not handled within 1 second: TypeError: Cannot read property 'cluster' of null

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1577]
rejected promise not handled within 1 second: TypeError: Cannot read property 'cluster' of null
extensionHostProcess.js:957
stack trace: TypeError: Cannot read property 'cluster' of null
	at EventEmitter.<anonymous> (/home/denis/p/vscode-openshift-tools/out/src/explorer.js:41:57)
	at EventEmitter.emit (events.js:203:13)
	at /home/denis/p/vscode-openshift-tools/out/src/util/watch.js:27:37
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by dgolovin** [comment]
Resolved with https://github.com/redhat-developer/vscode-openshift-tools/pull/1584.
