### ISSUE TITLE
An intermittent error reported when creating a new Project

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1595]
```
rejected promise not handled within 1 second: Error: Cannot resolve tree item for element 0/0:192.168.42.69:8443/0:p1
extensionHostProcess.js:957
stack trace: Error: Cannot resolve tree item for element 0/0:192.168.42.69:8443/0:p1
	at /snap/code/33/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:605:767
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

The project does not appear in the OpenShift Application Explorer tree after the error and refresh is required to see it.

**Comment by dgolovin** [comment]
Fixed, when we updated Application Explorer View to show only current context's resources.
