### ISSUE TITLE
Fix `Error: Cannot resolve tree item for element 0/0:cluster/0:project' in unit tests

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#1741]
```
rejected promise not handled within 1 second: Error: Cannot resolve tree item for element 0/0:cluster/0:project
extensionHostProcess.js:1048
stack trace: Error: Cannot resolve tree item for element 0/0:cluster/0:project
    at /snap/code/43/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:281
extensionHostProcess.js:1048
[GitHD] [20:34:44.312][Info] _onDidChangeActiveTextEditor with null or undefined editor
jenkins.js:337
rejected promise not handled within 1 second: Error: Cannot resolve tree item for element 0/0:cluster/0:goodvalue
extensionHostProcess.js:1048
stack trace: Error: Cannot resolve tree item for element 0/0:cluster/0:goodvalue
    at /snap/code/43/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:281
extensionHostProcess.js:1048
rejected promise not handled within 1 second: Error: Cannot resolve tree item for element 0/0:cluster/0:name&name
extensionHostProcess.js:1048
stack trace: Error: Cannot resolve tree item for element 0/0:cluster/0:name&name
    at /snap/code/43/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:281
extensionHostProcess.js:1048
rejected promise not handled within 1 second: Error: Cannot resolve tree item for element 0/0:cluster/0:project
extensionHostProcess.js:1048
stack trace: Error: Cannot resolve tree item for element 0/0:cluster/0:project
    at /snap/code/43/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:281
extensionHostProcess.js:1048
rejected promise not handled within 1 second: Error: Cannot resolve tree item for element 0/0:cluster/0:n123456789012345678901234567890123456789012345678901234567890123
extensionHostProcess.js:1048
stack trace: Error: Cannot resolve tree item for element 0/0:cluster/0:n123456789012345678901234567890123456789012345678901234567890123
    at /snap/code/43/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:652:281
```

**Comment by dgolovin** [comment]
Fixed via 1fbdd5867379061b48e5170928a624117d18b6ea.
