### ISSUE TITLE
Extension fails to activate when open workspace grows sufficiently large

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-openshift-tools#2059]
Happens to me on Fedora 33, looks like it's reaching the system limit for file watchers.

For me it started happening after opening this repo and 2 nodejs devfile starter projects in the same workspace. I have no idea if or when other systems/distros will run into their limits, but it might be something to watch out for.
```
[2021-03-22 14:43:38.274] [exthost] [error] Activating extension redhat.vscode-openshift-connector failed due to an error:
[2021-03-22 14:43:38.276] [exthost] [error] Error: ENOSPC: System limit for number of file watchers reached, watch '/home/jrichter/.kube'
	at FSWatcher.start (internal/fs/watchers.js:165:26)
	at Object.watch (fs.js:1329:11)
	at Function.watchFileForContextChange (/home/jrichter/.vscode/extensions/redhat.vscode-openshift-connector-0.2.4/out/src/util/watch.js:17:30)
	at new OpenShiftExplorer (/home/jrichter/.vscode/extensions/redhat.vscode-openshift-connector-0.2.4/out/src/explorer.js:43:38)
	at Function.getInstance (/home/jrichter/.vscode/extensions/redhat.vscode-openshift-connector-0.2.4/out/src/explorer.js:69:42)
	at Object.<anonymous> (/home/jrichter/.vscode/extensions/redhat.vscode-openshift-connector-0.2.4/out/src/openshift/openshiftItem.js:193:55)
	at Module.o._compile (/usr/share/code/resources/app/out/vs/loader.js:16:571)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1092:657)
	at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1061:334)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1057:567)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at r (/usr/share/code/resources/app/out/vs/loader.js:16:346)
	at Object.<anonymous> (/home/jrichter/.vscode/extensions/redhat.vscode-openshift-connector-0.2.4/out/src/openshift/cluster.js:25:25)
	at Module.o._compile (/usr/share/code/resources/app/out/vs/loader.js:16:571)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1092:657)
	at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1061:334)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1057:567)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at r (/usr/share/code/resources/app/out/vs/loader.js:16:346)
	at Object.<anonymous> (/home/jrichter/.vscode/extensions/redhat.vscode-openshift-connector-0.2.4/out/src/extension.js:21:19)
	at Module.o._compile (/usr/share/code/resources/app/out/vs/loader.js:16:571)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1051:10)
	at Module.load (internal/modules/cjs/loader.js:862:32)
	at Module._load (internal/modules/cjs/loader.js:774:14)
	at Function.Module._load (electron/js2c/asar.js:769:28)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1092:657)
	at Function.i._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1061:334)
	at Function.n._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1057:567)
	at Module.require (internal/modules/cjs/loader.js:899:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.r [as __$__nodeRequire] (/usr/share/code/resources/app/out/vs/loader.js:20:263)
	at p._loadCommonJSModule (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1062:631)
	at p._doActivateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:958:742)
	at p._activateExtension (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:957:822)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by dgolovin** [comment]
It is probably related to something else, because the extension watch the only file ~/.kube/config file. 
It is good point anyway, because even if watcher failed to initiate tracking for config file extension still should work. That would disable automatic update for Application Explorer and other views, but would not stop extension from activating.

**Comment by dgolovin** [comment]
Resolved already, see https://github.com/redhat-developer/vscode-openshift-tools/blob/86b47de8cd3dfbb2dfae536e40b0806e1e989874/src/explorer.ts#L59.
