### ISSUE TITLE
Change Context command fails when `/.kube/config is empty

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-openshift-tools#2060]
According to telemetry it fails with exception: 
```
Exception has occurred: TypeError: Cannot read property 'clusters' of undefined
t KubeConfigUtils.loadFromString (/home/denis/p/vscode-openshift-tools/node_modules/@kubernetes/client-node/dist/config.js:105:56)
	at KubeConfigUtils.loadFromFile (/home/denis/p/vscode-openshift-tools/node_modules/@kubernetes/client-node/dist/config.js:75:14)
	at KubeConfigUtils.loadFromDefault (/home/denis/p/vscode-openshift-tools/node_modules/@kubernetes/client-node/dist/config.js:231:22)
	at new KubeConfigUtils (/home/denis/p/vscode-openshift-tools/out/src/util/kubeUtils.js:12:14)
	at /home/denis/p/vscode-openshift-tools/out/src/openshift/cluster.js:90:31
	at Generator.next (<anonymous>)
	at /home/denis/p/vscode-openshift-tools/out/src/openshift/cluster.js:18:71
	at new Promise (<anonymous>)
	at /home/denis/p/vscode-openshift-tools/out/src/openshift/cluster.js:14:12
	at switchContext (/home/denis/p/vscode-openshift-tools/out/src/openshift/cluster.js:89:16)
	at Object.<anonymous> (/home/denis/p/vscode-openshift-tools/out/src/vscommand.js:52:63)
	at Generator.next (<anonymous>)
	at /home/denis/p/vscode-openshift-tools/out/src/vscommand.js:12:71
	at new Promise (<anonymous>)
	at /home/denis/p/vscode-openshift-tools/out/src/vscommand.js:8:12
	at /home/denis/p/vscode-openshift-tools/out/src/vscommand.js:44:84
	at S._executeContributedCommand (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:103774)
	at S.$executeContributedCommand (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:104212)
	at c._doInvokeHandler (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:10509)
	at c._invokeHandler (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:10201)
	at c._receiveRequest (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:8871)
	at c._receiveOneMessage (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:7673)
	at /snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:5782
	at g.fire (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at p.fire (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15443)
	at /snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:29119
	at g.fire (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at p.fire (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15443)
	at t._receiveMessage (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20693)
	at /snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17587
	at g.fire (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at l.acceptChunk (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12808)
	at /snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12156
	at Socket.E (/snap/code/59/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:12375)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
	at Pipe.callbackTrampoline (internal/async_hooks.js:120:14)
```

**Comment by dgolovin** [comment]
Cannot replicate. It sows empty quick pick now.

**Comment by dgolovin** [comment]
@odockal It shows welcome page with buttons now in OpenShift Application Explorer. If you click on Change Context button in view title, it asks you to login to a cluster if there is no config file yet or contexts in config file.

**Comment by dgolovin** [comment]
@odockal NM, works when there is no config file. Duplicate of #2603.
