### ISSUE TITLE
Build cannot download func dependency, if the project is checked out to a directory with a dot character

### ISSUE THREAD

**Issue by mkuznyetsov** [redhat-developer/vscode-openshift-tools#3527]
If this project is checked out to a directory, that has a dot in its path, e.g. `/home/user/redhat.vscode-openshift-connector`, build will fail at the stage of downloading `func` dependency:

```
...
Extracting /opt/app-root/src/redhat.vscode-openshift-connector-src/redhat.vscode-openshift-connector/out/tools-cache/func_linux_amd64 to /opt/app-root/src/redhat.vscode-openshift-connector-src/redhat.vscode-openshift-connector/out/tools/linux/func
Error: Unsupported extension for '/opt/app-root/src/redhat.vscode-openshift-connector-src/redhat.vscode-openshift-connector/out/tools-cache/func_linux_amd64'
    at /opt/app-root/src/redhat.vscode-openshift-connector-src/redhat.vscode-openshift-connector/out/src/downloadUtil/archive.js:34:24
    at new Promise (<anonymous>)
    at Archive.extract (/opt/app-root/src/redhat.vscode-openshift-connector-src/redhat.vscode-openshift-connector/out/src/downloadUtil/archive.js:16:16)
    at /opt/app-root/src/redhat.vscode-openshift-connector-src/redhat.vscode-openshift-connector/out/src/downloadUtil/downloadBinaries.js:43:37
...
```
seems like the condition checking for dot [here](https://github.com/redhat-developer/vscode-openshift-tools/blob/ef2b50ecf4e08a8f5a9acb5912d218038660d66a/src/downloadUtil/downloadBinaries.ts#L38) will be not working as intended in this case

**Comment by datho7561** [comment]
Thanks for reporting, I was able to reproduce the issue. Should be a pretty simple fix.
