### ISSUE TITLE
Support creating component from a multi-project github repository

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-openshift-tools#363]
using https://github.com/jboss-fuse/fuse-springboot-circuit-breaker-booster ,there are 2 springboot project name-service and greetings-service.
I would like to have these 2 seprated projects added as seprated components.

Currently, I can choose only the top-level folder when creating component 
![image](https://user-images.githubusercontent.com/1105127/48767830-e16d3100-ecb7-11e8-83ef-9a49a6adbe6f.png)

**Comment by jrichter1** [comment]
Not sure if vscode is able to let you choose between workspace subfolders. But you can get around it by opening both the subprojects directly.

**Comment by apupier** [comment]
seems workaround is not working, i've got (silent) build failures when opening on the specific subfolders and trying to create the component

```
"C:\Users\Aurelien Pupier\.vs-openshift\odo.exe" push --local c:\ws\workingDirectoryForTest\test-circuitBreaker-withFixedSpringbootdashboard\fuse-springboot-circuit-breaker-booster\name-service
Pushing changes to component: name-service
Please wait, building component....
+ set -eo pipefail
+ '[' -f /opt/app-root/src/.s2i/bin/assemble ']'
+ '[' -f /usr/local/s2i/assemble ']'
+ rm -rf /opt/app-root/src/.git
+ cp -a /opt/app-root/src/. /tmp/src
+ /usr/local/s2i/assemble
==================================================================
Starting S2I Java Build .....
Maven build detected
Initialising default settings /tmp/artifacts/configuration/settings.xml
Setting MAVEN_OPTS to -XX:+UseParallelOldGC -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError
Found pom.xml ... 
Running 'mvn -Dmaven.repo.local=/tmp/artifacts/m2 -s /tmp/artifacts/configuration/settings.xml -e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga -Dfabric8.skip=true package --batch-mode -Djava.net.preferIPv4Stack=true '
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[1mApache Maven 3.5.0 (Red Hat 3.5.0-4.3)[m
Maven home: /opt/rh/rh-maven35/root/usr/share/maven
Java version: 1.8.0_191, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.10.0-862.11.6.el7.x86_64", arch: "amd64", family: "unix"
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] Downloading: https://repo1.maven.org/maven2/com/redhat/fuse/boosters/fuse-springboot-circuit-breaker-booster-parent/7.0.0.redhat-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://repo1.maven.org/maven2/com/redhat/fuse/boosters/fuse-springboot-circuit-breaker-booster-parent/7.0.0.redhat-SNAPSHOT/fuse-springboot-circuit-breaker-booster-parent-7.0.0.redhat-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.redhat.fuse.boosters:name-service:[unknown-version]: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 6, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.redhat.fuse.boosters:name-service:[unknown-version]: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 6, column 13

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:382)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:400)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:391)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:78)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:511)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:221)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   
[ERROR]   The project com.redhat.fuse.boosters:name-service:[unknown-version] (/tmp/src/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.redhat.fuse.boosters:name-service:[unknown-version]: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 6, column 13 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:197)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:243)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1051)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:829)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:331)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:429)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:398)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:362)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:400)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:391)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:78)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:511)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:221)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:232)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:303)
	at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:193)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.redhat.fuse.boosters:fuse-springboot-circuit-breaker-booster-parent:pom:7.0.0.redhat-SNAPSHOT in central (https://repo1.maven.org/maven2)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:76)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:590)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:258)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:529)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:430)
	... 29 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
Aborting due to error code 1 for Maven build
failed to push component: name-service
```

the build requires the parent folders to be available in the pod to be built successfully

**Comment by apupier** [comment]
It seems to be a limitation of odo, see https://github.com/redhat-developer/odo/issues/1014

**Comment by apupier** [comment]
seems odo is capable of supporting this by using specific environment variables, see https://github.com/redhat-developer/odo/issues/1014#issuecomment-440357998

it would be nice if VS Code extension can provide these environment variables to support this use case.

**Comment by jeffmaury** [comment]
Need to understand how generic is this ?

**Comment by dgolovin** [comment]
> if I understand well, the build requires the parent folders to be available in the pod to be built successfully
Or it should be available from maven repository local ~/.m2 or remote.

**Comment by mohitsuman** [comment]
Not a priority anymore.
